services:
  - type: web
    name: kvant-messenger
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kvant-db
          property: connectionString

databases:
  - name: kvant-db
    plan: free
